### PR TITLE
Latest master from upstream

### PR DESCRIPTION
**Pull request by pombredanne**

### CODE REVIEW

**Comment by pombredanne** [comment]
@axiak @dcrosta @piskvorky and team : Thanks

**Comment by piskvorky** [comment]
Hey @pombredanne ... are you starting a new fork? Or what's going on with this repo?

**Comment by axiak** [comment]
Comparing this shows nothing's changed: https://github.com/axiak/pybloomfiltermmap/compare/master...pombredanne:master

@pombredanne if you want to contribute anything to mainline, let us know.

**Comment by pombredanne** [comment]
@axiak you wrote:

> Comparing this shows nothing's changed: axiak@master...pombredanne:master

This is normal since I just pulled in your latest code in my tracking master.
I have nothing to contribute atm... but be assured I will if I do!

@piskvorky Hey Radim :) I am not starting a new fork, I am just tracking the latest in my master and sent a thank you note to you all :P

**Pull request merged**
